### ISSUE TITLE
Please include README and tests in source tarball

### ISSUE THREAD

**Issue by Natureshadow** [libwilliam/flask-compress#19]
I am packaging and maintaining Flask-Compress for the Debian distribution.

It would be great if you could make sure to include all documentation, i.e. the README file, in future source tarballs (those uploaded to PyPI). Please also include the test suite.

Please also consider gpg-signing the tarballs uploaded to PyPI.

**Comment by libwilliam** [comment]
Awesome! Thank you for taking the time to do that.

I will try and have an updated package pushed out sometime tonight.

**Comment by Natureshadow** [comment]
It's ok if you do it with the next regular release ☺.

**Comment by Natureshadow** [comment]
Please do not forget to include the LICENSE.txt as well.

**Comment by Natureshadow** [comment]
OK, here's an update:

The package is close to an upload to Debian. However, the missing license in the source tarball has become a point of discussion. We could probably work around this, but maybe we don't have to.

How close are you to the 1.3.2 release? Do you think we can get a release, with the license and other text files included?

Another side note: According to current law, you are the copyright holder of the code you write. So you might want to put your name in the LICENSE file as copyright holder as well.

**Comment by libwilliam** [comment]
I just posted `v1.3.2` with your requested changes.

- Updated copyright information in LICENSE.txt
- Included LICENSE.txt in source tarball
- Included README.md in source tarball

The one thing left to do it GPG sign the package I put on PyPi. I'll do that that this morning.

**Comment by libwilliam** [comment]
The signed package is now up on PyPi. 

Thank you for taking the time to package this project!

Is there anything else you would like me to do?

**Comment by Natureshadow** [comment]
I don't think so. I will push the new version to the packaging repo and see what the sponsor has to say ☺.
