### ISSUE TITLE
Need to control when this fires

### ISSUE THREAD

**Issue by dagostinelli** [libwilliam/flask-compress#20]
A problem with Flask is the inability to order when after_request handlers fire.  Understandably, a user of flask-compress might want this to run at a certain time (such as after the response has been fully composed) and not arbitrarily. 

I'd like to request that Flask-Compress not always auto-register with app.after_request in init_app().  Instead, let there be a config flag that says "COMPRESS_AUTOREGISTER" and default it to True.  Then in init_app(), check this and don't call `app.after_request(self.after_request)` if it's False.

This allows the user of the library to purposefully call Compress.after_request at the proper time.

With this functionality in place, in my app, I would now be able to do this:
```
	@app.after_request
	def after_request(response):
		# do something (e.g. check a few things)
		response = compress.after_request(response)
		# do something more (e.g. add a digital signing signature to the header)
		return response
```

**Comment by libwilliam** [comment]
I added a `COMPRESS_REGISTER` option to `v1.4.0` to handle this scenario.

Thank you!

**Comment by dagostinelli** [comment]
Slam dunk!  Thank you!
