### ISSUE TITLE
Getting unicode error when enabling flask-compress on my application

### ISSUE THREAD

**Issue by tatsuhirosatou** [libwilliam/flask-compress#21]
Hello!

I am running my app on Heroku and was hoping to add gzip compression. I tried whitenoise first and although it didn't give any errors, the gzip compression was not working. Then I found your extension and was happy to see it is so simple. Thanks for making this. Unfortunately I am running into the following error: 

`UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte`

If a comment the line that add compress, then the app works again. 

![image](https://cloud.githubusercontent.com/assets/232527/21833085/d2c5032c-d77d-11e6-8393-08f6dd48cfa6.png)

**Comment by tatsuhirosatou** [comment]
Fixed it. It was this problem: https://github.com/mgood/flask-debugtoolbar/issues/83

**Comment by libwilliam** [comment]
Thank you for keeping this `Issue` updated. Sorry I wasn't able to reply until now.
