### ISSUE TITLE
So if we use nginx. We don't need flask-compress?

### ISSUE THREAD

**Issue by rlam3** [libwilliam/flask-compress#22]
So if we use nginx. We don't need flask-compress?

**Comment by libwilliam** [comment]
Likely no. NGINX (and other servers) have the option to compress the media for you automatically. This solution (flask-compress) is mainly for developers that don't have the option to configure their server for automatic compression.

**Comment by rlam3** [comment]
Would it make sense to use flask-compress in development environment since in development we aren't necessarily using nginx but rather the flask app itself. 

So would it make sense to just enable it there instead of the whole application when using the factory pattern? Maybe speed up the load times? Not sure if it would though...

Thanks!

**Comment by libwilliam** [comment]
If you do turn it on for development you would get a better sense of the actual payload size. Also, a lot of HTML viewers will automatically expand the HTML to a readable format when compressed so you won't be stuck looking at compressed data.

**Comment by rlam3** [comment]
Would you recommend that we use this in development then? Just to speed up the load time? For instance if your page needs to load a lot of divs or tables.. or a continuous scroll....

**Comment by libwilliam** [comment]
Compression is mainly needed to give the end-user the shortest load time possible. It will do the same for developers but it isn't as necessary.
